"""Offline: park.world -> ROS occupancy grid (park_map.pgm/.yaml) + a named
places table (park_places.yaml). Run once, or whenever park.world changes.

No simulator, no ground truth: reads the static world file only. Footprints use
per-family constant radii (all obstacle collisions in park.world are meshes, so
there is no SDF primitive radius to read). The costmap inflates these later --
we emit RAW footprints, no pre-inflation.
"""
import os
import sys
import argparse

from map_tools.sdf_parse import parse_models
from map_tools.occupancy_grid import Grid
from map_tools.mesh_bounds import footprint_dxdy

# Footprint radii in metres, BEFORE costmap inflation. See the plan for rationale.
# NOTE: the furniture entries here (bench/garden_table/lamp/trash_bin_1) are
# superseded by BOX_MESHES below -- build_grid boxes those families using the
# real mesh footprint instead. Left in place because test_radii still checks
# every family has a positive radius, and RADII has no other users to break.
RADII = {
    "arbolpartes4": 0.30,
    "tree_8": 0.45,
    "bench": 0.90,
    "garden_table": 0.60,
    "lamp": 0.20,
    "trash_bin_1": 0.25,
}

# Families stamped as yaw-oriented boxes, with their collision .dae (relative to
# the models_opt/ root). Everything else (trees, lamp, trash_bin_1) stays a disc
# via RADII. lamp (0.095 m wide) and trash_bin_1 (~0.10x0.06 m) are EXCLUDED here
# on purpose: at 0.15 m grid resolution their box footprint is sub-cell, so
# stamp_box can find zero (or ~1) cell centers inside it and the object nearly
# or entirely vanishes from the map. Discs still mark them correctly.
import os as _os
_MODELS_ROOT = _os.path.join(_os.path.dirname(__file__), "..", "models_opt")
BOX_MESHES = {
    "bench":        _os.path.join(_MODELS_ROOT, "bench", "Bench_1.dae"),
    "garden_table": _os.path.join(_MODELS_ROOT, "garden_table", "garden_table.dae"),
}
# Cache footprints so each .dae is parsed once.
_footprint_cache = {}
def _box_half_extents(family):
    if family not in _footprint_cache:
        dx, dy = footprint_dxdy(BOX_MESHES[family])
        _footprint_cache[family] = (dx / 2.0, dy / 2.0)
    return _footprint_cache[family]

# Families that become named goal destinations (not trees).
PLACE_FAMILIES = ("bench", "garden_table", "lamp", "trash_bin_1")


def build_grid(models, resolution=0.15, margin=5.0):
    xs = [m.world_x for m in models]
    ys = [m.world_y for m in models]
    g = Grid(min(xs) - margin, min(ys) - margin,
             max(xs) + margin, max(ys) + margin, resolution)
    for m in models:
        if m.family in BOX_MESHES:
            hx, hy = _box_half_extents(m.family)
            g.stamp_box(m.world_x, m.world_y, m.yaw, hx, hy)
        else:
            g.stamp_disc(m.world_x, m.world_y, RADII[m.family])
    return g


def build_places(models):
    places = {}
    for m in models:
        if m.family in PLACE_FAMILIES:
            places[m.name] = {"x": round(m.world_x, 3), "y": round(m.world_y, 3)}
    return places


def _write_places_yaml(places, path):
    with open(path, "w") as fh:
        fh.write("# Named goal destinations, map-frame metres. Generated by "
                 "extract_park_map.py.\n")
        for name in sorted(places):  # sorted only for stable file diffs (not display)
            p = places[name]
            fh.write("%s: {x: %.3f, y: %.3f}\n" % (name, p["x"], p["y"]))


def main(argv=None):
    ap = argparse.ArgumentParser(description="Extract park map + places from park.world")
    ap.add_argument("--world", default=os.path.join(
        os.path.dirname(__file__), "..", "natural_environments_ros_opt",
        "natural_enviroment", "worlds", "park.world"))
    ap.add_argument("--out-dir", default=os.path.join(
        os.path.dirname(__file__), "..", "maps"))
    ap.add_argument("--resolution", type=float, default=0.15)
    args = ap.parse_args(argv)

    os.makedirs(args.out_dir, exist_ok=True)
    models = parse_models(args.world)
    grid = build_grid(models, resolution=args.resolution)
    places = build_places(models)

    grid.write_pgm(os.path.join(args.out_dir, "park_map.pgm"))
    grid.write_yaml(os.path.join(args.out_dir, "park_map.yaml"), "park_map.pgm")
    _write_places_yaml(places, os.path.join(args.out_dir, "park_places.yaml"))
    print("wrote park_map.pgm/.yaml (%dx%d @ %.2f m) and park_places.yaml (%d places)"
          % (grid.width, grid.height, args.resolution, len(places)))
    return 0


if __name__ == "__main__":
    sys.exit(main())
