#!/usr/bin/env python3
"""Publish a DTM (.npy from map_tools/extract_dtm.py) as a height-coloured
PointCloud2, for eyeballing terrain relief in RViz.

One point per VALID cell, at the cell's world-frame centre, with z = the cell
height and an rgb colour ramped over the height range. NaN cells are skipped
entirely -- they mean "no mesh covered this cell", and emitting them at z=0
would draw a fake flat floor that reads as real terrain.

A coloured cloud rather than Markers on purpose: these grids are ~80k cells,
and a MarkerArray of that size makes RViz crawl, while a PointCloud2 of the
same data renders instantly.

Diagnostic tool. It reads a file and publishes; it subscribes to nothing, and
is not part of the navigation stack.

Typical use (park and lake terrain, plus the lake's water layer, each on its
own topic so they can be toggled independently in RViz):

    rosrun ... or plain python3:
    python3 scripts/publish_dtm_cloud.py --dtm maps/park_dtm.npy \
        --topic /dtm_cloud
    python3 scripts/publish_dtm_cloud.py --dtm maps/lake_dtm.npy \
        --topic /dtm_cloud
    python3 scripts/publish_dtm_cloud.py --dtm maps/lake_water.npy \
        --topic /water_cloud --colormap water
    python3 scripts/publish_dtm_cloud.py --dtm maps/lake_dtm.npy \
        --color-from maps/lake_slope.npy \
        --topic /slope_cloud --colormap slope

The slope layer is degrees, not metres, so it must never supply its own
geometry -- `--color-from` drapes its colour over the DTM's height geometry
instead, so the overlay sits ON the terrain rather than being plotted as its
own (nonsensical) elevation.

In RViz add a PointCloud2 display per topic, set Color Transformer to RGB8.

Vertical alignment: the DTM carries true world elevations, while the nav stack
is strictly 2D (base_link sits at z = 0). The two are each right in their own
frame but share no datum, so a lake DTM lifted to z ~= +5 draws *above* the
robot. `--z-offset` and `--z-align` shift the published z for DISPLAY ONLY;
`--z-align min|median` computes an offset that lands the minimum / median valid
height at z = 0, and that computed value is ADDED to `--z-offset`, so
`--z-align min --z-offset 0.5` puts the minimum at +0.5. Colours never move:
the ramp is always computed from the ORIGINAL, unshifted heights, so a given
colour means the same real-world elevation whatever the offset.
"""
import argparse
import os
import struct
import sys

import numpy as np
import rospy
from sensor_msgs.msg import PointCloud2, PointField
from std_msgs.msg import Header

# Grid geometry lives in the .yaml the extractor writes next to the .npy. Only
# a handful of scalars are needed, so this is parsed directly rather than
# pulling in PyYAML -- the file is generated by us and is strictly "key: value".
_NEEDED = ("resolution", "origin_x", "origin_y")


def load_grid_meta(npy_path, grid_meta_path=None):
    """(resolution, origin_x, origin_y) for `npy_path`.

    By default this reads the .yaml beside `npy_path` (the extractor's
    DTM-style yaml, with flat resolution/origin_x/origin_y/width/height keys).

    `grid_meta_path`, if given, overrides which yaml is read -- this is for
    rasters like `<world>_slope.npy` that hold values computed straight off
    the DTM array (same shape, origin, and resolution as `<world>_dtm.npy`)
    but whose own sibling yaml describes a DIFFERENT, resampled grid (the
    map_server-style PGM used for costmaps). In that case the geometry must
    come from the DTM's yaml, not the slope's own.
    """
    yaml_path = grid_meta_path or (os.path.splitext(npy_path)[0] + ".yaml")
    if not os.path.exists(yaml_path):
        raise IOError(
            "missing %s -- the DTM .npy carries no geometry of its own, so "
            "the .yaml written beside it by map_tools/extract_dtm.py is "
            "required to place the cloud." % yaml_path)
    meta = {}
    with open(yaml_path) as fh:
        for line in fh:
            line = line.strip()
            if not line or line.startswith("#") or ":" not in line:
                continue
            key, _, val = line.partition(":")
            key = key.strip()
            if key in _NEEDED:
                try:
                    meta[key] = float(val.strip())
                except ValueError:
                    pass
    missing = [k for k in _NEEDED if k not in meta]
    if missing:
        raise ValueError(
            "%s is missing %s -- this looks like a map_server-style yaml "
            "(image/origin:[x,y,z]/negate/...) rather than the DTM extractor's "
            "flat resolution/origin_x/origin_y format, so it does not carry "
            "the keys this loader needs. If %s is on a different grid than "
            "its own geometry (e.g. a slope .npy computed on the DTM grid), "
            "pass --grid-meta pointing at the correct DTM .yaml instead." %
            (yaml_path, ", ".join(missing), npy_path))
    return meta["resolution"], meta["origin_x"], meta["origin_y"]


def _ramp_terrain(t):
    """Blue -> cyan -> green -> yellow -> red over t in [0, 1].

    A perceptually ordered ramp so that "higher" reads as higher at a glance;
    the point of the display is comparing relief between two worlds.
    """
    r = np.clip(np.minimum(4.0 * t - 1.5, -4.0 * t + 4.5), 0.0, 1.0)
    g = np.clip(np.minimum(4.0 * t - 0.5, -4.0 * t + 3.5), 0.0, 1.0)
    b = np.clip(np.minimum(4.0 * t + 0.5, -4.0 * t + 2.5), 0.0, 1.0)
    return r, g, b


def _ramp_water(t):
    """Flat blue. The water layer is a constant-height plane, so a ramp over
    its (zero) range would be meaningless noise -- a single colour that reads
    as water is more honest."""
    one = np.ones_like(t)
    return 0.10 * one, 0.45 * one, 0.90 * one


# Absolute slope thresholds in DEGREES, matching map_tools/slope_costmap.py's
# warn_deg/lethal_deg defaults exactly. These must stay ABSOLUTE, never derived
# from the input array's own min/max/percentiles -- a relative ramp would make
# a flat world look artificially steep (or a steep one look flat).
SLOPE_SAFE_DEG = 10.0
SLOPE_LETHAL_DEG = 18.0


def _ramp_slope(t):
    """Green -> yellow -> orange -> red, keyed to ABSOLUTE slope in degrees.

    `t` here is degrees, NOT a normalised [0, 1] fraction -- build_cloud_points
    passes the raw slope values straight through for this colormap (see the
    `colormap == "slope"` branch below), so the thresholds below read directly
    as SLOPE_SAFE_DEG / SLOPE_LETHAL_DEG.

    < SLOPE_SAFE_DEG               -> green   (free, matches costmap's 0)
    SLOPE_SAFE_DEG..SLOPE_LETHAL_DEG -> green->yellow->orange ramp (priced)
    >= SLOPE_LETHAL_DEG            -> red     (lethal, matches costmap's 100)
    """
    deg = np.clip(t, SLOPE_SAFE_DEG, SLOPE_LETHAL_DEG)
    frac = (deg - SLOPE_SAFE_DEG) / (SLOPE_LETHAL_DEG - SLOPE_SAFE_DEG)
    # Safe cells (t < SLOPE_SAFE_DEG) collapse frac to 0, i.e. pure green.
    # Lethal cells (t >= SLOPE_LETHAL_DEG) collapse frac to 1, i.e. pure red.
    r = np.where(t < SLOPE_SAFE_DEG, 0.0, np.clip(2.0 * frac, 0.0, 1.0))
    g = np.where(t >= SLOPE_LETHAL_DEG, np.clip(2.0 * (1.0 - frac), 0.0, 1.0), 1.0)
    g = np.where(t < SLOPE_SAFE_DEG, 1.0, g)
    b = np.zeros_like(np.asarray(t, dtype=np.float64))
    return r, g, b


COLORMAPS = {"terrain": _ramp_terrain, "water": _ramp_water, "slope": _ramp_slope}

# Colormaps in this set are keyed to ABSOLUTE, real-world units (e.g. degrees)
# rather than the [0, 1] normalised fraction build_cloud_points otherwise
# computes from the data's own min/max. build_cloud_points passes the raw
# heights straight through to these instead of `t`.
ABSOLUTE_COLORMAPS = {"slope"}


Z_ALIGNMENTS = ("none", "min", "median")


def compute_align_offset(z, z_align):
    """The vertical shift that `z_align` asks for, from the valid cells of `z`.

    "min"/"median" return the offset that lands that statistic at zero; "none"
    returns 0.0, as does an all-NaN grid (there is nothing to align to).
    """
    if z_align == "none":
        return 0.0
    if z_align not in Z_ALIGNMENTS:
        raise ValueError("unknown --z-align %r" % (z_align,))
    finite = z[np.isfinite(z)]
    if finite.size == 0:
        return 0.0
    stat = finite.min() if z_align == "min" else np.median(finite)
    return -float(stat)


def build_cloud_points(z, resolution, origin_x, origin_y, colormap="terrain",
                       z_min=None, z_max=None, z_offset=0.0, color_z=None):
    """(N,4) float32 array of x, y, z, rgb-as-float for every valid cell.

    `z` supplies the point GEOMETRY (x, y, and height). By default the same
    array also supplies the colour ramp's scalar. Pass `color_z` (same shape
    as `z`) to instead DRAPE a different scalar's colour over `z`'s geometry
    -- e.g. slope degrees coloured on top of terrain heights, so the overlay
    sits on the real surface instead of being plotted as its own elevation.
    A cell that is NaN in EITHER array is dropped: a point cannot be placed
    without a height, and cannot be coloured without a value.

    `z_offset` is added to the published z only. The colour ramp (and so
    `z_min`/`z_max`, which are unshifted values in whichever array supplies
    colour) is computed from the original, unshifted values, so colour stays
    tied to the real underlying quantity.
    """
    if color_z is None:
        color_z = z
    elif color_z.shape != z.shape:
        raise ValueError(
            "geometry and colour rasters must be the same shape -- got "
            "geometry shape %r vs colour shape %r" % (z.shape, color_z.shape))

    valid = np.isfinite(z) & np.isfinite(color_z)
    n = int(valid.sum())
    if n == 0:
        return np.zeros((0, 4), dtype=np.float32)

    rows, cols = np.nonzero(valid)
    heights = z[rows, cols].astype(np.float64)
    color_vals = color_z[rows, cols].astype(np.float64)

    x = origin_x + (cols + 0.5) * resolution
    y = origin_y + (rows + 0.5) * resolution

    if colormap in ABSOLUTE_COLORMAPS:
        # Keyed to real-world units (e.g. slope degrees), not a min/max
        # fraction of THIS grid -- pass the raw values straight through so the
        # colour means the same absolute thing on every world.
        t = color_vals
    else:
        lo = color_vals.min() if z_min is None else z_min
        hi = color_vals.max() if z_max is None else z_max
        span = hi - lo
        # A perfectly flat layer (span 0, e.g. the water plane) would divide by
        # zero; map it all to the middle of the ramp instead.
        t = np.full_like(color_vals, 0.5) if span <= 0.0 else (color_vals - lo) / span
        t = np.clip(t, 0.0, 1.0)

    r, g, b = COLORMAPS[colormap](t)
    rgb_int = ((np.uint32(255 * r).astype(np.uint32) << 16)
               | (np.uint32(255 * g).astype(np.uint32) << 8)
               | np.uint32(255 * b).astype(np.uint32))
    # PointCloud2 packs rgb as a float32 whose BITS are the uint32 -- a cast
    # would change the bits, so reinterpret instead.
    rgb_f = rgb_int.astype(np.uint32).view(np.float32)

    # Shift AFTER the ramp above so the colour keeps meaning real elevation.
    return np.column_stack([x, y, heights + z_offset, rgb_f]).astype(np.float32)


def make_cloud_msg(points, frame_id, stamp):
    """A dense, unordered PointCloud2 from an (N,4) x/y/z/rgb array."""
    header = Header(stamp=stamp, frame_id=frame_id)
    fields = [
        PointField("x", 0, PointField.FLOAT32, 1),
        PointField("y", 4, PointField.FLOAT32, 1),
        PointField("z", 8, PointField.FLOAT32, 1),
        PointField("rgb", 12, PointField.FLOAT32, 1),
    ]
    msg = PointCloud2()
    msg.header = header
    msg.height = 1
    msg.width = len(points)
    msg.fields = fields
    msg.is_bigendian = False
    msg.point_step = 16
    msg.row_step = msg.point_step * msg.width
    msg.is_dense = True
    msg.data = np.ascontiguousarray(points, dtype=np.float32).tobytes()
    return msg


def main(argv=None):
    ap = argparse.ArgumentParser(
        description="Publish a DTM .npy as a height-coloured PointCloud2")
    ap.add_argument("--dtm", required=True, help="path to a DTM .npy")
    ap.add_argument("--color-from", default=None,
                    help="path to a .npy of the SAME shape as --dtm whose "
                         "values drive the colour ramp instead of --dtm's own "
                         "heights -- e.g. a slope .npy coloured over the DTM's "
                         "geometry, so the overlay drapes on the real terrain "
                         "surface instead of being plotted as its own "
                         "elevation. --z-min/--z-max then clamp THIS raster's "
                         "domain. A cell NaN in either raster is dropped. "
                         "Default: colour comes from --dtm itself (unchanged "
                         "behaviour).")
    ap.add_argument("--grid-meta", default=None,
                    help="yaml to read grid geometry (resolution/origin_x/"
                         "origin_y) from, overriding the default of the "
                         "sibling <dtm-stem>.yaml. Needed for rasters like "
                         "<world>_slope.npy, which are computed on the DTM "
                         "grid but whose own sibling yaml describes a "
                         "different, resampled grid -- point this at the "
                         "matching <world>_dtm.yaml instead.")
    ap.add_argument("--topic", default="/dtm_cloud")
    ap.add_argument("--frame", default="map")
    ap.add_argument("--rate", type=float, default=1.0,
                    help="republish rate in Hz (default 1.0)")
    ap.add_argument("--colormap", default="terrain", choices=sorted(COLORMAPS))
    ap.add_argument("--z-min", type=float, default=None,
                    help="force the colour-ramp low end, as an UNSHIFTED "
                         "world-frame height (--z-offset/--z-align do not "
                         "move it); use the same value for two worlds to make "
                         "their colours comparable")
    ap.add_argument("--z-max", type=float, default=None,
                    help="force the colour-ramp high end, as an UNSHIFTED "
                         "world-frame height (see --z-min)")
    ap.add_argument("--z-offset", type=float, default=0.0,
                    help="display-only shift added to every published z "
                         "(default 0.0 = today's behaviour, unshifted). "
                         "Colours are unaffected.")
    ap.add_argument("--z-align", default="none", choices=Z_ALIGNMENTS,
                    help="compute a shift from the valid cells: 'min' lands "
                         "the minimum height at z=0, 'median' the median, "
                         "'none' (default) computes nothing. The computed "
                         "value is ADDED to --z-offset, so '--z-align min "
                         "--z-offset 0.5' puts the minimum at +0.5.")
    args = ap.parse_args(argv if argv is not None else rospy.myargv()[1:])

    if args.rate <= 0:
        ap.error("--rate must be positive")

    z = np.load(args.dtm)
    color_z = np.load(args.color_from) if args.color_from else None
    if color_z is not None and color_z.shape != z.shape:
        raise ValueError(
            "--color-from %s has shape %r, but --dtm %s has shape %r -- "
            "they must be the same grid" %
            (args.color_from, color_z.shape, args.dtm, z.shape))
    resolution, origin_x, origin_y = load_grid_meta(args.dtm, args.grid_meta)
    total_offset = args.z_offset + compute_align_offset(z, args.z_align)
    points = build_cloud_points(z, resolution, origin_x, origin_y,
                                colormap=args.colormap,
                                z_min=args.z_min, z_max=args.z_max,
                                z_offset=total_offset, color_z=color_z)
    if len(points) == 0:
        rospy.logwarn("%s has no valid cells -- publishing an empty cloud",
                      args.dtm)

    finite = z[np.isfinite(z)]
    rospy.init_node("dtm_cloud_publisher", anonymous=True)
    rospy.loginfo("DTM %s: %d x %d @ %.3f m, %d valid cells",
                  os.path.basename(args.dtm), z.shape[1], z.shape[0],
                  resolution, len(points))
    if finite.size:
        rospy.loginfo("  z %.4f .. %.4f  (relief %.4f m)",
                      finite.min(), finite.max(), finite.max() - finite.min())
    # A shifted run must be obvious in the log, not a silent mystery in RViz.
    rospy.loginfo("  z-offset %+.4f m (--z-offset %+.4f, --z-align %s)",
                  total_offset, args.z_offset, args.z_align)
    if finite.size:
        rospy.loginfo("  published z %.4f .. %.4f  (relief unchanged, "
                      "colours from unshifted heights)",
                      finite.min() + total_offset, finite.max() + total_offset)
    rospy.loginfo("  publishing on %s in frame %s at %.2f Hz",
                  args.topic, args.frame, args.rate)

    # latch=True so an RViz started later still gets the cloud without waiting
    # for the next tick; the periodic republish covers RViz restarts too.
    pub = rospy.Publisher(args.topic, PointCloud2, queue_size=1, latch=True)
    rate = rospy.Rate(args.rate)
    while not rospy.is_shutdown():
        pub.publish(make_cloud_msg(points, args.frame, rospy.Time.now()))
        try:
            rate.sleep()
        except rospy.ROSInterruptException:
            break
    return 0


if __name__ == "__main__":
    sys.exit(main())
